# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 107207bf41475fbf232efa6102a1e58370a722ee7de86697cc139e45b2b6e3417141f6bebd219347c73a66b129a89aa9a4147ba3873f751f83ebc3a688244355

test:
  secret_key_base: 150733f0a49759ce44b42ee6568f583b9941996be95659b7bfb5d10adc8c27b9389bb8f5a250b0f84530c4cbf73441fe0a2ee717ee077c9694c408be7453b6cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
